[Main]
##
## NOTE: If this ini file does not get loaded by the game, whether this file don't exist or game failed to load it.. 
##       It will use the default values that are mentioned below.
##

Type = 1

# The values change the way you enter to the menu...
#
# 0-) "DEFAULT", 1-) "CUSTOM" - Custom will allow you to choose two keybinds to activate, instead of typing "TELEPORTER". By default, This option is 0

Keybind1 = 162
Keybind2 = 75

# Keybinds change be customizable, you can pick any keyboard key.. By default, these options are "163" and "75" (Left CTRL + K)
# The list of Keybinds are listed all in this website of documentation: https://www.gta-modding.com/san_andreas/tutorials/virtual_key_codes.html
# Enjoy using this script.. :)

[Teleport 1]

X =-1777.82
Y =6546.52
Z =7.57089
Angle =0

[Teleport 2]

X = 0.0
Y = 0.0
Z = 0.0
Angle = 0.0

[Teleport 3]

X =15576
Y =-7579.1
Z =4.53308
Angle =0


[Teleport 4]

X =1795.89
Y =-2140.71
Z =13.5469
Angle =0


[Teleport 5]

X =14218.8
Y =-7804.26
Z =5.05958
Angle =0


[Teleport 6]

X = 0.0
Y = 0.0
Z = 0.0
Angle = 0.0
