; Important!!!
; Make sure Encode is UTF-8, recommended using Notepad++.

; "WeaponID" = Weapon Type ID, not Model ID.
; "Name" = Weapon Name display in RZL-Trainer.

[1]
WeaponID     = 96	
Name         = VCbrassknuckle

[2]
WeaponID     = 105	
Name         = VCkatana

[3]
WeaponID     = 108	
Name         = VCpython

WeaponID     = 80	
Name         = LCfist		

[4]
WeaponID     = 81	
Name         = LCbat		

[5]
WeaponID     = 82	
Name         = LCcolt45	

[6]
WeaponID     = 83	
Name         = LCshotgun	

[7]
WeaponID     = 84	
Name         = LCuzi		

[8]
WeaponID     = 85	
Name         = LCak47		

[9]
WeaponID     = 86	
Name         = LCm16		

[10]
WeaponID     = 87	
Name         = LCsniper	

[11]
WeaponID     = 88	
Name         = LCrocketla	

[12]
WeaponID     = 89	
Name         = LCflame		

[13]
WeaponID     = 90	
Name         = LCgrenade	

[14]
WeaponID     = 91	
Name         = LCmolotov	

[15]
WeaponID     = 93	
Name         = LCbomb		


[16]
WeaponID     = 95	
Name         = VCfist			
[17]
WeaponID     = 96	
Name         = VCbrassknuckle
[18]
WeaponID     = 97	
Name         = VCscrewdriver	
[19]
WeaponID     = 98	
Name         = VCgolfclub		
[20]
WeaponID     = 99	
Name         = VCnitestick		
[21]
WeaponID     = 100	
Name         = VCknifecur		
[22]
WeaponID     = 101	
Name         = VCbat			
[23]
WeaponID     = 102	
Name         = VChammer		
[24]
WeaponID     = 103	
Name         = VCcleaver		
[25]
WeaponID     = 104	
Name         = VCmachete		
[26]
WeaponID     = 105	
Name         = VCkatana		
[27]
WeaponID     = 106	
Name         = VCchnsaw		
[28]
WeaponID     = 107	
Name         = VCcolt45		
[29]
WeaponID     = 108	
Name         = VCpython	
[30]
WeaponID     = 109	
Name         = VCchromegun		
[31]
WeaponID     = 110	
Name         = VCshotgspa		
[32]
WeaponID     = 111	
Name         = VCbuddyshot		
[33]
WeaponID     = 112	
Name         = VCtec9			
[34]
WeaponID     = 113	
Name         = VCuzi			
[35]
WeaponID     = 114	
Name         = VCingramsl		
[36]
WeaponID     = 115	
Name         = VCmp5lng		
[37]
WeaponID     = 116	
Name         = VCruger			
[39]
WeaponID     = 117	
Name         = VCm4			
[40]
WeaponID     = 118	
Name         = VCsniper		
[41]
WeaponID     = 119	
Name         = VClaser			
[42]
WeaponID     = 120	
Name         = VCrocketla		
[43]
WeaponID     = 121	
Name         = VCflame			
[44]
WeaponID     = 122	
Name         = VCm60			
[45]
WeaponID     = 123	
Name         = VCminigun		
[46]
WeaponID     = 125	
Name         = VCgrenade		
[47]
WeaponID     = 126	
Name         = VCteargas		
[48]
WeaponID     = 127	
Name         = VCmolotov		
[49]
WeaponID     = 128	
Name         = VCmissile		
[50]
WeaponID     = 129	
Name         = VCgrenade2		
[51]
WeaponID     = 130	
Name         = VCcamera		

[51]
WeaponID     = 134	
Name         = LSfist				
[52]
WeaponID     = 135	
Name         = LSbrassknuckle	
[53]
WeaponID     = 136	
Name         = LSchisel			
[54]
WeaponID     = 137	
Name         = LShockeystick		
[55]
WeaponID     = 138	
Name         = LSnitestick			
[56]
WeaponID     = 139	
Name         = LSknifecur			
[57]
WeaponID     = 140	
Name         = LSbat				
[58]
WeaponID     = 141	
Name         = LShandaxe		
[59]
WeaponID     = 142	
Name         = LScleaver			
[60]
WeaponID     = 143	
Name         = LSmachete			
[61]
WeaponID     = 144	
Name         = LSkatana		
[62]
WeaponID     = 145	
Name         = LSchnsaw		
[63]
WeaponID     = 146	
Name         = LSglock17		
[64]
WeaponID     = 147	
Name         = LSpython		
[65]
WeaponID     = 148	
Name         = LSchromegun			
[66]
WeaponID     = 149	
Name         = LSshotgspa			
[67]
WeaponID     = 150	
Name         = LSbuddyshot			
[68]
WeaponID     = 151	
Name         = LStec9				
[69]
WeaponID     = 152	
Name         = LSuzi				
[70]
WeaponID     = 153	
Name         = LSingramsl			
[71]
WeaponID     = 154	
Name         = LSmp5k			
[72]
WeaponID     = 155	
Name         = LSak47				
[73]
WeaponID     = 156	
Name         = LSm4			
[74]
WeaponID     = 157	
Name         = LSsniper		
[75]
WeaponID     = 158	
Name         = LSlaser				
[76]
WeaponID     = 159	
Name         = LSrocketla			
[77]
WeaponID     = 160	
Name         = LSflame				
[78]
WeaponID     = 161	
Name         = LSm60				
[79]
WeaponID     = 162	
Name         = LSminigun			
[80]
WeaponID     = 164	
Name         = LSgrenade			
[81]
WeaponID     = 165	
Name         = LSteargas			
[82]
WeaponID     = 166	
Name         = LSmolotov			
[83]
WeaponID     = 167	
Name         = LSmissile			
[84]
WeaponID     = 168	
Name         = LSgrenade2			
[85]
WeaponID     = 169	
Name         = LScamera		

[86]
WeaponID     = 173	
Name         = VSfist			
[87]
WeaponID     = 174	
Name         = VSbrassknuckle	
[88]
WeaponID     = 175	
Name         = VSbutt_knife	
[89]
WeaponID     = 176	
Name         = VSgolfclub		
[90]
WeaponID     = 177	
Name         = VSnitestick		
[91]
WeaponID     = 178	
Name         = VSknifecur		
[92]
WeaponID     = 179	
Name         = VSbat			
[93]
WeaponID     = 180	
Name         = VShandaxe		
[94]
WeaponID     = 181	
Name         = VSgaff			
[95]
WeaponID     = 182
Name         = VSmachete		
[96]
WeaponID     = 183
Name         = VSkatana		
[97]
WeaponID     = 184
Name         = VSchnsaw		
[98]
WeaponID     = 185
Name         = VSberetta		
[99]
WeaponID     = 186
Name         = VSpython		
[100]
WeaponID     = 187
Name         = VSchromegun		
[101]
WeaponID     = 188
Name         = VSshotgspa		
[102]
WeaponID     = 189
Name         = VSbuddyshot		
[103]
WeaponID     = 190
Name         = VSskorpion		
[104]
WeaponID     = 191
Name         = VSuzi			
[105]
WeaponID     = 192
Name         = VSingramsl		
[106]
WeaponID     = 193
Name         = VSmp5lng		
[107]
WeaponID     = 194
Name         = VSak47			
[108]
WeaponID     = 195
Name         = VSm16			
[109]
WeaponID     = 196
Name         = VSsniper		
[110]
WeaponID     = 197
Name         = VSlaser			
[111]
WeaponID     = 198
Name         = VSrocketla		
[112]
WeaponID     = 199
Name         = VSflame			
[113]
WeaponID     = 200
Name         = VSm249			
[114]
WeaponID     = 201
Name         = VSminigun		
[115]
WeaponID     = 203
Name         = VSgrenade		
[116]
WeaponID     = 204
Name         = VSteargas		
[117]
WeaponID     = 205
Name         = VSmolotov		
[118]
WeaponID     = 206
Name         = VSmissile		
[119]
WeaponID     = 207
Name         = VSlandmine		
[120]
WeaponID     = 208
Name         = VSseamine		


; etc.........
; Maximum [4095]