##
## NOTE: If this ini file does not get loaded by the game, whether this file don't exist or game failed to load it.. 
##       It will use the default values that are mentioned below.
##
##       [VC_ROB] will use MALE01 as default ped (not to make game crash)
##       [X_IMPEX] will use RCCAM as default for delivering. Respective vehicles: Securicar, Moonbeam, Coach, Flatbed, Linerunner, Trashmaster, Patriot, MrWhoope, Blista, Mule, Yankee, Bobcat, Dodo, Bus, Rumpo, Pony 
##       The second garage is respectively: Sentinel, Cheetah, Banshee, Idaho, Infernus, Taxi, Kuruma, Stretch, Perennial, Stinger, Manana, Landstalker, Stallion, BF Injection, Cabbie, Esperanto
##       [STARTGM] will use 0 as default. Which is no skip. 1 is Freeroam, 2 is Discovery, 3 is American Truck Simulator.

[STARTGM]

SkipToGamemode=1

[VC_ROB]

ID=48346

[X_IMPEX]

IMPEX1=20229
IMPEX2=20211
IMPEX3=20183
IMPEX4=20196
IMPEX5=20205
IMPEX6=20243
IMPEX7=20217
IMPEX8=20212
IMPEX9=20176
IMPEX10=20214
IMPEX11=20246
IMPEX12=20177
IMPEX13=20189
IMPEX14=20179
IMPEX15=20228
IMPEX16=20222

IMPEX17=20230
IMPEX18=20182
IMPEX19=20173
IMPEX20=20198
IMPEX21=20199
IMPEX22=20238
IMPEX23=20200
IMPEX24=20237
IMPEX25=20218
IMPEX26=20236
IMPEX27=20207
IMPEX28=20201
IMPEX29=20234
IMPEX30=20175
IMPEX31=20180
IMPEX32=20192